### ISSUE TITLE
conflict between docker-py and docker python modules

### ISSUE THREAD

**Issue by ynixon** [shelleg/ansible-role-portainer#10]
`
TASK [shelleg.ansible_role_portainer : Deploy Portainer to remote] *************
fatal: [remote]: FAILED! => {"changed": false, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module. It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
`
Any idea how to solve this ?

**Comment by hagzag** [comment]
@ynixon not sure this is related to this role specifically, I think it related to one of your other roles which install `docker-py`
